### ISSUE TITLE
User is routed to a different page on successful login attempt

### ISSUE THREAD

**Issue by brianhersh** [brianhersh/CEN-Project#22]

**Comment by brianhersh** [comment]
User will be routed to a page that has the graph information (with the line graph) after inputting valid username-password combo found in database and pressing the login button.

**Comment by FredderickB** [comment]
made progress on creating the route to the chart pages, next step is to have the user go directly to the chart route after succesful login/sign in.

**Comment by brianhersh** [comment]
User is now successfully routed to /charts when the login button is pushed with a username-password combo found in the back end's database
